services:
  linuxserver-common:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - UMASK_SET=022           # Control permissions of new files and directories
      - TZ=America/Los_Angeles  # Specify a timezone to use EG Europe/London.
      - PUID=1026               # ID of user to take ownership of application/files
      - PGID=101                # GID of user to take ownership of application/files
    restart: on-failure