services:
  wireguard:
    extends:
      file: ../_common/compose.yaml
      service: linuxserver-common
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1